### ISSUE TITLE
[Tutorial] Spaced Repetition Algorithm: A Three‐Day Journey from Novice to Expert

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki#472]
I translated my tutorial of spaced repetition algorithm research into English. Could you help me check it? @user1823, @Expertium and everyone interested in the mechanism of FSRS.

Link: https://github.com/open-spaced-repetition/fsrs4anki/wiki/Spaced-Repetition-Algorithm:-A-Three%E2%80%90Day-Journey-from-Novice-to-Expert

**Comment by Expertium** [comment]
Can you tell me how to edit that page and then use those edits to submit a pull request? I think there is a way to do that, but I don't know how.

**Comment by L-M-Sherlock** [comment]
<img width="820" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/368ccc0f-3187-49ea-8b1f-ad27c225b208">

I loosen the permission of editing the wiki. Could you try to edit it?

**Comment by Expertium** [comment]
I'll try to submit a PR later, but first I want to address this:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/ef1ed927-423c-41a1-93ca-ecf0fa596f19)
First of all, it's not clear what "learning efficiency" means here. Second of all, even if "learning efficiency" means "retention", it's still ambiguous.
1) Imagine that retention was 40%, and now it's 80%. You could say "retention has increased by 40%", meaning "new retention is equal to old retention **plus** 40%".
2) Imagine that retention was 40%, and now it's 56%. You could say "retention has increased by 40%", meaning "new retention is equal to old retention **multiplied** by 1.4".

**Comment by Expertium** [comment]
Also, I don't think the part about SM-4 is necessary.

**Comment by Expertium** [comment]
@L-M-Sherlock I have edited the page, you can compare the new version to the old. I have removed the part about SM-4 as I think it's not necessary, and I have removed everything after "State Transition" as it is not suitable for an introductory article, it's not something that a layperson can quickly grasp. Other than that, I mostly just changed wording. I will edit more later.

**Comment by L-M-Sherlock** [comment]
> First of all, it's not clear what "learning efficiency" means here. Second of all, even if "learning efficiency" means "retention", it's still ambiguous.

It is cited from the video of Osmosis: https://www.youtube.com/watch?v=cVf38y07cfk. I cite this resource to briefly introduce the effect of spaced repetition to readers. Because I don't want to cite too many details from academic literature.

> Also, I don't think the part about SM-4 is necessary.

I prefer to keep it in its place, because most people don't know why Woz proposed SM-3+. SM-4 is the simplest example.

> I have removed everything after "State Transition" as it is not suitable for an introductory article

Considering that some readers may have academic backgrounds, I would like to keep this section.

Another reason is that this article was translated from my Chinese article, so I don't want to remove an entire section.

**Comment by Expertium** [comment]
Also, this
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/6806e047-cdf5-4bc3-a23d-7481dad4f067)
It says "retrievability", but previously you made the disctinction between "retrievability" and "retention", and this stuff here is retention.

> Considering that some readers may have academic backgrounds, I would like to keep this section.

It would be better to have 2 articles - "easy" version and "hard" version of the article. KIt in the "hard" version.

**Comment by Expertium** [comment]
> It is cited from the video of Osmosis: https://www.youtube.com/watch?v=cVf38y07cfk. I cite this resource to briefly introduce the effect of spaced repetition to readers. Because I don't want to cite too many details from academic literature.

If even you don't know what it means exactly, then it's best to remove it.

**Comment by L-M-Sherlock** [comment]
> It would be better to have 2 articles an "easy" version and a "hard" version of the article. Keep it in the "hard" version.

You are right. It should be retention. Here I made a concession to treat retention as an approximation of retrievability.

> It would be better to have 2 articles an "easy" version and a "hard" version of the article. Keep it in the "hard" version.

Yeah. I plan to post the easy version in reddit and keep the hard version in wiki.

**Comment by Expertium** [comment]
Alright, I will bring SM-4 and the stuff at the end back. But I still think that "40% more efiiciency" should be removed, unless you are confident that you know exactly what it means.

**Comment by L-M-Sherlock** [comment]
OK. I will deal with it after a meeting.

**Comment by L-M-Sherlock** [comment]
I bring SM-4 back and add a warning for the hardest part: [Beginners Stop Here](https://github.com/open-spaced-repetition/fsrs4anki/wiki/Spaced-Repetition-Algorithm:-A-Three%E2%80%90Day-Journey-from-Novice-to-Expert#beginners-stop-here)

**Comment by Expertium** [comment]
"For longer review intervals, it takes a long time to make them stable." What does this mean?

**Comment by L-M-Sherlock** [comment]
If I(4) = 1 year, SM-4 needs to collect reviews with Ivl = 1 year to optimize it. It costs more time to converge than those short intervals' optimization, which collects reviews more easily.

**Comment by Expertium** [comment]
Yeah, that's pretty much what I thought. But then these 2 points are the same, no?
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/04b40a55-987c-4403-af2c-99b8609e7511)

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/32575846/989faede-9b73-497e-8e9e-e6a8401335ee)

Woz thought they are different: https://supermemo.guru/wiki/First_adaptable_spaced_repetition_algorithm:_Algorithm_SM-4#Rigid_SuperMemo_4

**Comment by Expertium** [comment]
I did a few surface-level changes. I will take a deeper look and rewrite some more stuff later.

**Comment by L-M-Sherlock** [comment]
OK. I will find some serious evidences for that.

**Comment by Expertium** [comment]
By the way, maybe we should this formula for the total estimated knowledge of notes?
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/ca46e6f1-fb2e-47c7-a61d-cf753e51528f)
Though if one of the cards is in the learning stage, it will set the probability to 0.

**Comment by Expertium** [comment]
I edited the article some more, though it still gives off a "I ran all of this through DeepL" vibe. Oh well. @user1823, your help would be appreciated.

**Comment by L-M-Sherlock** [comment]
> And I still recommend removing the "40% more efficiency" thing and replacing it with something else.

I have replaced the image with quotes from literatures:

- Rea & Modigliani 1985, [“The effect of expanded versus massed practice on the retention of multiplication facts and spelling lists”](https://github.com/doc/psychology/spaced-repetition/1985-rea.pdf):

> A test immediately following the training showed superior performance for the distributed group (70% correct) compared to the massed group (53% correct). These results seem to show that the spacing effect applies to school-age children and to at least some types of materials that are typically taught in school.

- Donovan & Radosevich 1999, [“A meta-analytic review of the distribution of practice effect: Now you see it, now you don’t”](https://gwern.net/doc/psychology/spaced-repetition/1999-donovan.pdf):

> According to Donovan & Radosevich’s meta-analysis of spacing studies, the effect size for the spacing effect is d = 0.42. This means that the average person getting distributed training remembers better than about 67% of the people getting massed training. This effect size is nothing to sneeze at-in education research, effect sizes as low as d = 0.2 are considered “practically significant”, while effect sizes above d = 1 are rare.

**Comment by Expertium** [comment]
I don't have anything else to add, so here's what I would do: you can either make a Reddit post to get attention to this article, or you can try to find a native English speaker who knows a lot about spaced repetition to proofread the article, and then make a Reddit post.

**Comment by user1823** [comment]
I have edited the first part of the page. I will make further edits when I get more time in the future.

Just to save the link, I am posting the link to the Chinese version here: https://zhuanlan.zhihu.com/p/556020884

**Comment by Expertium** [comment]
@user1823 I apologize if I'm being annoying, but I think it would be nice to release this article right as the new version of Anki comes out, so I would appreciate it if you went over the article this week. I'm sure Sherlock will appreciate it too.

**Comment by user1823** [comment]
I have made more edits. I think that it is now ready to be widely circulated (after disabling the option that allows anyone to edit).

**Comment by Expertium** [comment]
@L-M-Sherlock this link is broken
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/fc0961b3-d0d8-40c6-a405-3b42bba43b7d)

**Comment by Expertium** [comment]
I read the second paper and couldn't find this quote:
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/dc07d0ec-0761-4454-8268-2a75d59b5de5)
If this is your own wording, then you should change the formatting, as right now it looks like a quote.
Also, according to the paper, the average effect size is 0.46, not 0.42.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/2194f875-bf9a-4d06-a794-9a52413eee15)

**Comment by L-M-Sherlock** [comment]
> I read the second paper and couldn't find this quote:

I quote it from https://gwern.net/spaced-repetition#distributed:~:text=Donovan%E2%80%89%26%E2%80%89Radosevich1999%2C%20%E2%81%A0%E2%80%9CA%20meta%2Danalytic%20review%20of%20the%20distribution%20of%20practice%20effect%3A%20Now%20you%20see%20it%2C%20now%20you%20don%E2%80%99t%E2%80%9D%E2%81%A0%3A

**Comment by Expertium** [comment]
I would recommend replacing it with the quote from the study itself.

> The overall mean weighted effect size was 0.46, with a 95% confidence interval that extended from 0.42 to 0.50.

And after that you add "In practice, it means that around 63% of people who use spaced repetition will get better results than people who use massed repetition." Note that I did the math myself to convert Cohen's d to common language effect size. For Cohen' d=0.46, common language effect size would be around 62.5%, assuming the data is normally distributed.

**Comment by L-M-Sherlock** [comment]
> @L-M-Sherlock this link is broken

I fixed it. Could you try it again?

> I would recommend replacing it with the quote from the study itself.

Could you help me modify the texts? I'm coding for the auto disperse siblings after sync for 23.10.

**Comment by Expertium** [comment]
> I fixed it. Could you try it again?

It works now.

> Could you help me modify the texts?

Ok, I edited the page just now.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/f188a127-0a3a-42a3-a378-ecc323730e9e)

**Comment by Expertium** [comment]
@L-M-Sherlock are you sure about _I_? Shouldn't it be "stability after the first interval"?
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/6c2741b6-c9d0-4c55-96e8-5568f9c0d8dc)

**Comment by L-M-Sherlock** [comment]
> are you sure about _I_? Shouldn't it be "stability after the first review"? And C should be the ratio of stabilities, not intervals.

I'm sure because interval is equal to stability in the early stage of SuperMemo. You can check this section: https://supermemo.guru/wiki/Two_components_of_memory#Proof_by_Murakowski

**Comment by Expertium** [comment]
Ok, I edited it back, but there is still a problem.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/23504af0-a42e-4d14-b5e7-84205b59d81c))
People will likely ask "So is C_i a ratio of intervals or an increase in stability?"

**Comment by L-M-Sherlock** [comment]
In the model, C_i is an increase in stability. In the algorithm, C_i is a ratio of intervals. To disambiguate, it former is renamed to SInc in the remaining section.

**Comment by Expertium** [comment]
> In the model, C_i is an increase in stability. In the algorithm, C_i is a ratio of intervals.

So in this equation
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/38916afc-a53f-412d-bf1c-a68cf89b9330)
C_i is a ratio of intervals, and in the algorithm, it is the increase of stability, right?

**Comment by Expertium** [comment]
Ok, I edited it
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/1e2aa3b0-648b-4c1c-83fe-610e6226862b)

**Comment by Expertium** [comment]
Ok, I think that's about it. I recommend you to go over the article one more time and then maybe post it on r/Anki.

**Comment by AnKingMed** [comment]
I'll try and review this weekend. You all speak pretty good English for not being native! Where are the rest of you from? I know Sherlock is from China as we've had some discussions in Chinese :)

**Comment by user1823** [comment]
@AnKingMed, feedback on things that are ambiguous/ difficult to understand is welcome.

For things that obviously wrong and/or grammar/word-choice issues, you can edit the page yourself using the `Edit` button at the top of the page. There won't be many such issues though.

> Where are the rest of you from?

I am from India and Expertium is from Russia.

**Comment by Expertium** [comment]
Btw @AnKingMed don't forget about this one

**Comment by AnKingMed** [comment]
I haven't! Just got sick over the weekend and didn't get much done. It's on my todo list though!

**Comment by AnKingMed** [comment]
Really enjoyed this. 

Few suggestions: day 1 and 2 were pretty easy to understand. Day 3 was very complicated. Might be worth adding a more simple version of what’s going on with all the math with each step so the casual reader doesn’t have to break it down. 

It doesn’t connect to how this progressed to FSRS. I think that would be a valuable addition

**Comment by L-M-Sherlock** [comment]
> Day 3 was very complicated.

Day 3 is a concise version of my paper. So it is very complicated. It requires prior knowledge, such as machine learning, stochastic process and optimal control.

**Comment by Expertium** [comment]
> Day 3 was very complicated.

I advised Sherlock to remove averything after "Beginners Stop Here" warning, but he wanted to keep it.

> It doesn’t connect to how this progressed to FSRS. I think that would be a valuable addition

Agree.

**Comment by AnKingMed** [comment]
> I advised Sherlock to remove averything after "Beginners Stop Here" warning, but he wanted to keep it.

I think this is still valuable information. I would just add a "casual readers" type of summary for that section. Boil it down to the basics for those that don't understand all that prior knowledge.

**Comment by user1823** [comment]
My suggestion would be to replace this section with a summary (the type of summary Anking suggested) and create a new page for the details.

**Comment by L-M-Sherlock** [comment]
> I would just add a "casual readers" type of summary for that section.

Oh, I'm not sure what's the level of casual readers.

**Comment by Expertium** [comment]
> Oh, I'm not sure what's the level of casual readers.

Anything like the two images below are far too complicated for the average reader.
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/98499d73-8182-4c4e-b94f-827e48cbd59e)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/83031600/b9008cc5-a040-48cf-9e20-3e63b95c6877)

**Comment by AnKingMed** [comment]
Yes and that entire section went mostly over my head but you can add a box at the end that says something like “In simple terms, this is essentially saying that x, y, z” and just have a couple sentence summary

**Comment by L-M-Sherlock** [comment]
https://www.reddit.com/r/Anki/comments/17u01ge/spaced_repetition_algorithm_a_threeday_journey/
